// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	MessageHeader
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageHeader struct {
	// the message id
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	// message type
	MessageType string `protobuf:"bytes,2,opt,name=MessageType,json=messageType" json:"MessageType,omitempty"`
}

func (m *MessageHeader) Reset()                    { *m = MessageHeader{} }
func (m *MessageHeader) String() string            { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()               {}
func (*MessageHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageHeader) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageHeader) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

type Message struct {
	Header  *MessageHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Content []byte         `protobuf:"bytes,2,opt,name=Content,json=content,proto3" json:"Content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageHeader)(nil), "message.MessageHeader")
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x1c, 0xb9,
	0x78, 0x7d, 0x21, 0x4c, 0x8f, 0xd4, 0xc4, 0x94, 0xd4, 0x22, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0x4c, 0x17, 0x21, 0x05, 0x2e, 0x6e, 0xa8, 0x82,
	0x90, 0xca, 0x82, 0x54, 0x09, 0x26, 0xb0, 0x04, 0x77, 0x2e, 0x42, 0x48, 0x29, 0x98, 0x8b, 0x1d,
	0xaa, 0x42, 0x48, 0x8f, 0x8b, 0x2d, 0x03, 0x6c, 0x0c, 0xd8, 0x00, 0x6e, 0x23, 0x31, 0x3d, 0x98,
	0xb5, 0x28, 0x96, 0x04, 0x41, 0x55, 0x09, 0x49, 0x70, 0xb1, 0x3b, 0xe7, 0xe7, 0x95, 0xa4, 0xe6,
	0x95, 0x80, 0x0d, 0xe6, 0x09, 0x62, 0x4f, 0x86, 0x70, 0x93, 0xd8, 0xc0, 0xee, 0x34, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xf3, 0x06, 0xd0, 0x8c, 0xb8, 0x00, 0x00, 0x00,
}
