// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageHeader struct {
	// the message id
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// message type
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	// the time of creating
	Timestamp int64 `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// tag for other need
	Tag                  string   `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageHeader) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageHeader) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type MessageRoute struct {
	// where the message come from
	Source string `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	// where the message will broadcasted to
	Group string `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	// where the message come to
	Target string `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	// what's the operation on resource
	Operation string `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
	//what's the resource want to operate
	Resource             string   `protobuf:"bytes,5,opt,name=Resource,proto3" json:"Resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRoute) Reset()         { *m = MessageRoute{} }
func (m *MessageRoute) String() string { return proto.CompactTextString(m) }
func (*MessageRoute) ProtoMessage()    {}
func (*MessageRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRoute.Unmarshal(m, b)
}
func (m *MessageRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRoute.Marshal(b, m, deterministic)
}
func (m *MessageRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRoute.Merge(m, src)
}
func (m *MessageRoute) XXX_Size() int {
	return xxx_messageInfo_MessageRoute.Size(m)
}
func (m *MessageRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRoute.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRoute proto.InternalMessageInfo

func (m *MessageRoute) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MessageRoute) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *MessageRoute) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *MessageRoute) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *MessageRoute) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type Message struct {
	Header               *MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Router               *MessageRoute  `protobuf:"bytes,2,opt,name=Router,proto3" json:"Router,omitempty"`
	Content              []byte         `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetRouter() *MessageRoute {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageHeader)(nil), "message.MessageHeader")
	proto.RegisterType((*MessageRoute)(nil), "message.MessageRoute")
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xb1, 0x4e, 0xc3, 0x40,
	0x0c, 0x86, 0x95, 0xa4, 0x4d, 0x88, 0xdb, 0x22, 0x64, 0x41, 0x75, 0x42, 0x0c, 0x55, 0xa6, 0x2e,
	0x64, 0x28, 0x8f, 0x40, 0x25, 0xe8, 0x80, 0x90, 0x8e, 0xbc, 0xc0, 0x51, 0xac, 0xd0, 0x21, 0xb9,
	0xd3, 0xe5, 0x32, 0xb0, 0xf2, 0x00, 0x3c, 0x33, 0x8a, 0xe3, 0x52, 0xd1, 0xcd, 0xbf, 0xfd, 0x9f,
	0xbe, 0xdf, 0x3e, 0x58, 0x34, 0xd4, 0x75, 0xa6, 0xa6, 0xd2, 0x79, 0x1b, 0x2c, 0x66, 0x22, 0x8b,
	0x3d, 0x2c, 0x5e, 0xc6, 0xf2, 0x99, 0xcc, 0x07, 0x79, 0xbc, 0x84, 0x78, 0xb7, 0x55, 0xd1, 0x2a,
	0x5a, 0xe7, 0x3a, 0xde, 0x6d, 0x11, 0x61, 0x52, 0x7d, 0x39, 0x52, 0x31, 0x77, 0xb8, 0xc6, 0x3b,
	0xc8, 0xab, 0x43, 0x43, 0x5d, 0x30, 0x8d, 0x53, 0xc9, 0x2a, 0x5a, 0x27, 0xfa, 0xd4, 0xc0, 0x2b,
	0x48, 0x2a, 0x53, 0xab, 0x09, 0x3f, 0x18, 0xca, 0xe2, 0x27, 0x82, 0xb9, 0x50, 0xb4, 0xed, 0x03,
	0xe1, 0x12, 0xd2, 0x37, 0xdb, 0xfb, 0x3d, 0x09, 0x48, 0x14, 0x5e, 0xc3, 0xf4, 0xc9, 0xdb, 0xde,
	0x09, 0x6d, 0x14, 0x83, 0xbb, 0x32, 0xbe, 0xa6, 0xc0, 0xac, 0x5c, 0x8b, 0x1a, 0x62, 0xbc, 0x3a,
	0xf2, 0x26, 0x1c, 0x6c, 0x2b, 0xb8, 0x53, 0x03, 0x6f, 0xe1, 0x42, 0x53, 0x37, 0x52, 0xa6, 0x3c,
	0xfc, 0xd3, 0xc5, 0x77, 0x04, 0x99, 0x04, 0xc2, 0x12, 0xd2, 0x4f, 0x5e, 0x9d, 0xb3, 0xcc, 0x36,
	0xcb, 0xf2, 0x78, 0xaa, 0x7f, 0x87, 0xd1, 0xe2, 0xc2, 0x7b, 0x48, 0x79, 0x09, 0xcf, 0x21, 0x67,
	0x9b, 0x9b, 0x73, 0x3f, 0x4f, 0xb5, 0x98, 0x50, 0x41, 0xf6, 0x68, 0xdb, 0x40, 0xed, 0x98, 0x7e,
	0xae, 0x8f, 0xf2, 0x3d, 0xe5, 0xaf, 0x78, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x22, 0x9e, 0xe6,
	0xbc, 0x9b, 0x01, 0x00, 0x00,
}
